<?php 
$title = 'Kích hoạt tài khoản'; include 'includes/header.php';
?>
<div id="content">
    
    <div class="row"> <!-- MAIN ROW -->
        <!-- Left Collumn -->
        <div class="col-sm-3">
        </div><!--end .col-sm-3 left collumn -->

        <div class="col-sm-6"><!-- MAIN COLLUMN-->
            <div class="panel panel-success">
            <div class="panel-body">
            <?php 
                if(isset($_GET['email'], $_GET['hash']) && filter_var($_GET['email'], FILTER_VALIDATE_EMAIL) && strlen($_GET['hash']) == 32) {
                    // Store $_GET
                    $email = mysqli_real_escape_string($db_connect, $_GET['email']);
                    $hash = mysqli_real_escape_string($db_connect, $_GET['hash']);
                    
                    //Check if the activation link is expired.
                    $query =  "SELECT expired FROM user WHERE email = '{$email}'";
                    $result = mysqli_query($db_connect, $query); confirm_query($result, $query);
                    if(mysqli_num_rows($result) == 1) {
                        //Save registration timestamp into variable
                        list($expired) = mysqli_fetch_array($result, MYSQLI_NUM);
                        //Parse into a Unix timestamp
                        $expired_time = strtotime($expired);
                        //Period of time from registration timestamp up to now.
                        $period = $expired_time - time();
                        if($period < 0) {
                            //Activation link will be expired after 24 hours.
                            echo "<div class='alert-danger alert' role='alert'>   
                                        Link kích hoạt đã hết hạn. <a href='resend-activation-code.php'>Gửi lại link kích hoạt?</a>
                                </div>";
                        } else {
                            //Activate user
                            $query = "UPDATE user SET active = NULL, expired = NULL WHERE email = '{$email}' AND active = '{$hash}' LIMIT 1";
                            $result = mysqli_query($db_connect, $query); confirm_query($result, $query);
                            if(mysqli_affected_rows($db_connect) == 1) {
                                //If activate successfully
                                echo "<div class='alert-success alert alert-dismissible' role='alert'>
                                            <button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button>    
                                            <span class='glyphicon glyphicon-ok'></span> Tài khoản của bạn đã được kích hoạt. Hệ thống sẽ chuyển đến trang <a href='http://idabong.com/login.php'>đăng nhập</a> sau 10s.
                                        </div>";    
                            } else {
                                echo "<div class='alert-danger alert' role='alert'>   
                                        <strong>Xin lỗi!</strong> Tài khoản không thể kích hoạt.
                                    </div>";
                            }
                        }//END if period > 86400
                    } else {
                        echo "<div class='alert-danger alert' role='alert'>   
                                Đã có lỗi xảy ra. Vui lòng thử kích hoạt sau.
                            </div>";
                    }//END if the activation link is expired
                    
                } else {
                    // If activate link is wrong, redirect to home page
                    redirect_to();
                }
            ?>
            
          </div><!--end .panel-body -->
        </div><!--end .panel -->
        
        </div> <!--end MAIN COLLUMN -->
            
        <!-- right collumn -->
        <div class="col-sm-3">
        </div><!--end .col-sm-3 right collumn -->

    </div><!-- end MAIN ROW -->
</div><!--end content-->

<?php include 'includes/footer.php';?>

<!--******** Additional Script ********-->

<!-- Pleace this snippet right after opening the head tag to make it work properly -->

<!-- This code is licensed under GNU GPL v3 -->
<!-- You are allowed to freely copy, distribute and use this code, but removing author credit is strictly prohibited -->
<!-- Generated by http://insider.zone/tools/client-side-url-redirect-generator/ -->

<!-- REDIRECTING STARTS -->
<noscript>
    <meta http-equiv="refresh" <?php echo "content='10;URL=".BASE_URL."login.php'";?>>
</noscript>
<!--[if lt IE 9]><script type="text/javascript">var IE_fix=true;</script><![endif]-->
<script type="text/javascript">
    var url = "http://localhost/idabong-v1.0/login.php";
    var delay = "10000";
    window.onload = function ()
    {
        setTimeout(GoToURL, delay);
    }
    function GoToURL()
    {
        if(typeof IE_fix != "undefined") // IE8 and lower fix to pass the http referer
        {
            var referLink = document.createElement("a");
            referLink.href = url;
            document.body.appendChild(referLink);
            referLink.click();
        }
        else { window.location.replace(url); } // All other browsers
    }
</script>
<!-- Credit goes to http://insider.zone/ -->
<!-- REDIRECTING ENDS -->

</body>

</html>





